# This is a basic workflow to help you get started with Actions

name: RSDKv5 Android Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  v5-android:
    runs-on: windows-latest
    steps:
      - name: Checkout repository Android
        uses: actions/checkout@v2
        with:
          submodules: recursive    
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Download libvorbis for easier includes
        run: |
          Invoke-WebRequest -Uri "https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.7.zip" -OutFile "libvorbis.zip"
          Expand-Archive -Path libvorbis.zip -DestinationPath ./dependencies/android/
          Rename-Item ./dependencies/android/libvorbis-1.3.7 libvorbis
      - name: Download GLEW
        run: |
          Invoke-WebRequest -Uri "https://github.com/nigels-com/glew/releases/download/glew-2.2.0/glew-2.2.0-win32.zip" -OutFile "GLEW.zip"
          Expand-Archive -Path GLEW.zip -DestinationPath ./dependencies/android/
          Rename-Item ./dependencies/android/glew-2.2.0 glew          
      - name: Run vcpkg
        run: |
          vcpkg install libogg:x86-windows-static
          vcpkg integrate install          
      - name: Download SDL2
        run: |
          Invoke-WebRequest -Uri "https://libsdl.org/release/SDL2-devel-2.0.14-VC.zip" -OutFile "SDL2.zip"
          Expand-Archive -Path SDL2.zip -DestinationPath ./dependencies/android/
          Rename-Item ./dependencies/android/SDL2-2.0.14 SDL2
      - name: Move & Copy stuff
        run: |
          Copy-Item -Path ./dependencies/android/app/jni/src/dependencies/android\* -Destination ./dependencies/
          Copy-Item -Path ./dependencies/android/config_types.h -Destination ./dependencies/android/libogg/include/ogg/
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11
      - name: Build RSDKv5 Android
        working-directory: ./android
        run: |
          ./gradlew.bat assembleDebug --no-daemon -PABIFILTERS="armeabi-v7a;arm64-v8a"
      - name: Upload artifact Android
        uses: actions/upload-artifact@v2
        with:
          name: v5-android
          path: ./android/app/build/outputs/apk
  