name: Build RSDKv5 webOS

on:
  workflow_dispatch:

jobs:
  build-webos:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: | 
        sudo apt update -y && sudo apt-get install build-essential cmake libglew-dev libglfw3-dev libtheora-dev portaudio19-dev libc6-dev-armel-cross -y && npm install -g @webos-tools/cli
        mkdir -p dependencies/webOS/SDL2
        wget -qO - https://github.com/webosbrew/SDL-webOS/releases/download/release-2.30.8-webos.3/SDL2-2.30.8-webos-abi.tar.gz | tar -C dependencies/webOS/SDL2 -zxvf -

    - name: Download webOS NDK
      uses: robinraju/release-downloader@v1.9
      with:
        repository: "openlgtv/buildroot-nc4"
        latest: true
        fileName: "arm-webos-linux-gnueabi_sdk-buildroot-x86_64.tar.gz"
        out-file-path: "/tmp"

    - name: Extract webOS NDK
      shell: bash
      working-directory: /tmp
      run: |
        tar xzf arm-webos-linux-gnueabi_sdk-buildroot-x86_64.tar.gz
        ./arm-webos-linux-gnueabi_sdk-buildroot/relocate-sdk.sh

    - name: Prepare Build
      shell: bash
      run: |
        git clone https://github.com/xiph/ogg.git "dependencies/webOS/libogg"
        git clone -b theora-1.1 --single-branch https://github.com/xiph/theora.git "dependencies/android/libtheora"
        git clone https://github.com/RSDKModding/Sonic-Mania-Decompilation SonicMania
        cd SonicMania
        rm -rf dependencies/RSDKv5
        ln -sf ../.. dependencies/RSDKv5
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        
    - name: Build
      shell: bash
      # Execute the build.
      run: |
        . /tmp/arm-webos-linux-gnueabi_sdk-buildroot/environment-setup
        cd SonicMania
        cmake -B build -DPLATFORM=webOS -DRETRO_MOD_LOADER=ON -DWITH_RSDK=ON -DCMAKE_BUILD_TYPE=Release
        cd build
        make

    # Deprecated but leaving commented here for other reasons.   
    #- name: Bundle an IPK
    #  shell: bash
    #  run: |
    #    OUTPUT_FILE=bin/webOS/SDL2/gamecontrollerdb.txt sh webos/gen_gamecontrollerdb.sh
    #    cp -u webos/icon.png bin/webOS/SDL2
    #    cp -u webos/splash.png bin/webOS/SDL2
    #    cp -u webos/appinfo.json bin/webOS/SDL2
    #    ares-package bin/webOS/SDL2
    #    PATH=/bin:/usr/bin python3 webos/gen_manifest.py -a bin/webOS/SDL2/appinfo.json -p *.ipk -o webosbrew.manifest.json

    - name: Upload Artifacts (webOS)
      id: upload_artifacts_webos
      uses: actions/upload-artifact@v4
      with:
        name: webOS-artifacts
        path: |
          *.ipk
          webosbrew.manifest.json
